### ISSUE TITLE
Add /sprefresh <stockpile> command

### ISSUE THREAD

**Issue by Romboter** [Tkaixiang/Storeman-Bot#102]
We have /spsettimeleft but I think its a bit hard to use for laypeople considering it takes a unix timestamp.

Proposing a /sprefresh <stockpile> that works the same as pressing the refresh timer button.

**Comment by Tkaixiang** [comment]
Added in 85a2fac89618e019ffde5aa4a86f815f8468ac61
`/sprefresh` can either refresh all stockpiles or only a specified stockpile
