### ISSUE TITLE
Crash: 9mm

### ISSUE THREAD

**Issue by tehruttiger** [Tkaixiang/Storeman-Bot#12]
![image](https://user-images.githubusercontent.com/75584675/150647625-abe44669-4ab5-4527-8849-103e5c33d018.png)

Attempting to add target for 9mm seems to always cause a crash

/sptarget item:9mm minimum_amount:50

**Comment by Tkaixiang** [comment]
This looks like a Discord bug. I was unable to reproduce it unfortunately

**Comment by tehruttiger** [comment]
I'll try again with the newest version and report back.
