### ISSUE TITLE
Logging to file on server

### ISSUE THREAD

**Issue by tehruttiger** [Tkaixiang/Storeman-Bot#14]
Is it possible to have a text log file on the server that lists the date and time and user and command run? This would help with bug fixing and also this log cannot be modified unlike Discord messages that can be edited or deleted except by the server admin.

**Comment by Tkaixiang** [comment]
I will not be creating a seperate file for logging since docker saves all logs to it's own file. I suggest looking at [here](https://stackoverflow.com/questions/41144589/how-to-redirect-docker-container-logs-to-a-single-file)

All logging has also been vastly improved to show what is going on :)
