### ISSUE TITLE
win32 dependencies not met.

### ISSUE THREAD

**Issue by AlpBilgin** [Tkaixiang/Storeman-Bot#145]
Hello

I ran this from source code on a Win10 machine with an activated venv. I let pip fetch the deps using the requirements file. On first try global hotkeys dependency complained that win32con was missing. I fixed it by manually adding pywin32 package to the local venv.

It may be helpful to other people to add it to the requirements too.

**Comment by Tkaixiang** [comment]
Heyo, it seems like this issue is meant for the Stockpiler repo. I will update the requirements.txt there

**Comment by AlpBilgin** [comment]
thanks I still haven't gotten used to the split repo.
