### ISSUE TITLE
/sptarget weird capitalization

### ISSUE THREAD

**Issue by tehruttiger** [Tkaixiang/Storeman-Bot#15]
When adding a target, it offers you choices that are all lower case, but still capitalizes the word Crate.  Either make crate lower case, or better yet display the names on the choice buttons as they are capitalized in the spreadsheet (even if the bot makes them lower case for the name matching).

**Comment by Tkaixiang** [comment]
Fixed in d64339f4b8c8c2bec2e6737facdde583a340ca76
