### ISSUE TITLE
Add /spcode or something

### ISSUE THREAD

**Issue by tehruttiger** [Tkaixiang/Storeman-Bot#16]
Would be helpful for an (optional) command to set the stockpile code for each stockpile.

This stockpile code would show under the title of the stockpile.  Potentially eliminates the need for a separate discord channel showing all the codes.

Ashfields 1 (last scan: 6 hours ago) [Expiry: in 6 hours] [a.k.a LOGIMAIN1]
Stockpile Code: 123456
Medical
89 - Soldier Supplies crate
Resource
27 - Garrison Supplies crate
.......

**Comment by Tkaixiang** [comment]
Added in the latest update

**Comment by tehruttiger** [comment]
Updated bot and saw the new command in /sphelp but doesn't appear to be registered as a command yet.

**Comment by tehruttiger** [comment]
Disregard last comment, wasn't aware of Discord delay when adding commands
