### ISSUE TITLE
Add new items for update 51 and 52

### ISSUE THREAD

**Issue by instantae** [Tkaixiang/Storeman-Bot#191]
I've created a patch for the stockpilerbot to add in missing U51/U52 items and given them the following IDs in the ItemNumbering.csv file, however they show up as "undefined" in the storemanbot discord channel while the results of the screengrab correctly identifies them

ID# - Name
93 - Maintenance supplies
272 - Havoc Charge
273 - Havoc Charge Detonator
274 - Mounted Fissura gd.I
275 - Silverhand Lordscar - Mk. X
276 - O'Brien V.190 Knave
277 - Dunne Dousing Engine 3r
278 - R-12b "Salva"

**Comment by Tkaixiang** [comment]
Stockpiler now supports everything except for 275 and 276. Please DM me on Discord if you do have the Stockpiler icons for these
