### ISSUE TITLE
Delay between processing stockpiles

### ISSUE THREAD

**Issue by tehruttiger** [Tkaixiang/Storeman-Bot#20]
There appears to be a significant delay between the processing of queued updates.  I'm not sure if the processing itself is taking a long while or there is a hangup between processing jobs.  If we send 4 or 5 updates (always waiting for Sent to bot successfully message in between) they always queue up and take sometimes 5 or more minutes for each to process.  The size of the stockpile and number of items doesn't seem to impact the amount of delay.

**Comment by Tkaixiang** [comment]
Should be fixed
