### ISSUE TITLE
/spfind item

### ISSUE THREAD

**Issue by tehruttiger** [Tkaixiang/Storeman-Bot#31]
Request for new command called something like /spfind

Run /spfind flatbed and it would respond by telling you all stockpiles that have the item and in what quantity at each one

Ideally, if you ask for a vehicle or shippable, /spfind flatbed would tell you "In VIPER1 you have 1 flatbed and 2 flatbed crates" or similar message

**Comment by tehruttiger** [comment]
If implemented, the message should be private/dismissable

**Comment by Tkaixiang** [comment]
Added in a04124d7bed83848f8a9bf3b5dabecd54299247c
