### ISSUE TITLE
Make bot more forgiving on commands

### ISSUE THREAD

**Issue by tehruttiger** [Tkaixiang/Storeman-Bot#34]
If you add a stockpile, bot should be more forgiving when you run a command against the name.

For example:

If you add a stockpile called Arty1
You should be able to run a command against arty1 and the command should succeed

Behavior noticed when trying to apply /spcode add

**Comment by Tkaixiang** [comment]
Fixed in 35a380048b1dc136026f49595d00ba9c72de9701
