### ISSUE TITLE
Stockpile expiration ghost

### ISSUE THREAD

**Issue by tehruttiger** [Tkaixiang/Storeman-Bot#38]
Ran the purge command and removed and readded channel to start fresh.  A few minutes later I got a message that a stockpile was going to expire.  When I tried to remove that stockpile I was told it didn't exist.  Maybe purge doesn't clear the expiration warning data.

**Comment by Tkaixiang** [comment]
Fixed in 7ea6a062732ea74d836b4d7bffa428dd06ab6ade
