### ISSUE TITLE
Expiration timer automation

### ISSUE THREAD

**Issue by tehruttiger** [Tkaixiang/Storeman-Bot#39]
Foxhole resets a stockpile timer any time an item is added OR removed.  This means that ANY change of a stockpile means the timer has been reset.  With this in mind, we suggest the expiration timer be reset automatically when a scan happens if the contents of that stockpile has changed according to some basic logic.

Scenario:
I scan STOCKPILE1
1 crate shirts

Two hours later I scan STOCKPILE1 again
1 crate shirts
1 crate bmats

Expiration timer changes to "expires in 46 to 48 hours"

We can't say 46 hours or 48 hours because we don't know specifically when the bmat crate was added, but we know that the timer definitely is between 46 and 48 hours.

This will greatly reduce the amount of manually refreshing needing to be done on the stockpile bot using the refresh buttons.  That will make the expiration warnings much more relevant and accurate with way fewer false positives.

If a stockpile is refreshed manually with the button in discord, then you can safely use that exact time until it is manually refreshed again OR it is scanned and has changed and the logic above applies.  If an expiration warning needs to be generated, it can say "this stockpile might expire in 10 min" or whatever the thresholds are.  It should always be safest and generate a warning when the LOWER time reaches the threshold.

**Comment by Tkaixiang** [comment]
Added in bee46c7d372645e6477870905dba4588e91923f5
