### ISSUE TITLE
Bot crashes when adding target

### ISSUE THREAD

**Issue by tehruttiger** [Tkaixiang/Storeman-Bot#47]
Attempting to add a target for ammo with a period breaks the bot.

Tried /sptarget set with 7.92mm and 12.7mm.  Both cause a crash.

**Comment by tehruttiger** [comment]
![Screenshot_20220222-150121_JuiceSSH](https://user-images.githubusercontent.com/75584675/155234865-3aad26d7-195d-42b5-afc5-1ef2cf10575d.jpg)

**Comment by Tkaixiang** [comment]
Fixed in f2d6f2ed1cced1488024318a3e594b6fd3c5552e
