### ISSUE TITLE
Stockpiles disappearing

### ISSUE THREAD

**Issue by tehruttiger** [Tkaixiang/Storeman-Bot#54]
Stockpile listings will disappear, unsure of the cause yet.  You'll just look at the channel and one or more will just be missing.  You can still submit them successfully, so they do still appear to exist in the database (trying to add them via discord command confirms they already exist).

Strongly suggest an entry added to the logs for when any message is deleted, along with maybe why the bot is deleting it in order to track the issue down.  Maybe also add a similar message for when it edits messages: ie "Editing message number 4 (Stockpile name) due to new submission" or "Editing message number 6 (Stockpile name) due to order change"

I don't know stockpile messages are being deleted or modified/overwritten.

**Comment by tehruttiger** [comment]
Stockpiles disappearing seems to be associated with a scan happening and the bot modifying the wrong message and therefore overwriting and deleting a stockpile.  Sometimes results in two copies of one stockpile (one apparently overwriting a now missing stockpile).

**Comment by Tkaixiang** [comment]
Would really appreciate anymore information on this if anyone else experiences this.

**Comment by Tkaixiang** [comment]
Finally fixed in 4cc0023a3e8eaf175352aa9fa87514b6989d08c3
Thanks to @tehruttiger for the detailed repro steps
