### ISSUE TITLE
Timer on each stockpile

### ISSUE THREAD

**Issue by tehruttiger** [Tkaixiang/Storeman-Bot#7]
Suggestion: Add a timer that counts up for each stockpile showing when it was last scanned.  This could be instead of or in addition to the Last Scanned time.

Like it says "last scanned 15 min ago"

Wouldn't need to count by the second or anything.  If less than 5 min say "just now"

**Comment by Tkaixiang** [comment]
Implemented in 0a52ec2f337dd118255ee7b0ff2c27c4d7ee1535
