### ISSUE TITLE
More degrees between red X and green check

### ISSUE THREAD

**Issue by tehruttiger** [Tkaixiang/Storeman-Bot#9]
Suggestion to make other items between red X and green check.

If stock is between 0-49% use red X
Between 50-74% use orange icon
Between 75-99% use yellow icon
100% or more use green check

Easier to tell what is really needed at a glance
0/100 is more important than 99/100 but both currently show red Xs

**Comment by Tkaixiang** [comment]
Implemented in 593534e6096256d63c5e0377040b647f4d3f58d5

**Comment by tehruttiger** [comment]
I think you might want to swap the yellow exclamation point for a simple yellow circle like the current orange one.  The yellow exclamation point implies danger, even though it is higher stock than the orange.

**Comment by Tkaixiang** [comment]
Fixed in 450c4adf93ca822d9645a252844ced28927bfca0
